model_name_or_path: __MODEL_NAME_OR_PATH__
stage: sft
do_train: true
finetuning_type: full
deepspeed: configs/train/deepspeed-zero3.json
dataset: __DATASET__
dataset_dir: __DATASET_DIR__
template: qwen
train_on_prompt: false
mask_history: false
cutoff_len: __CUTOFF_LEN__
overwrite_cache: true
preprocessing_num_workers: 1
output_dir: __OUTPUT_DIR__
logging_steps: __LOGGING_STEPS__
save_strategy: __SAVE_STRATEGY__
overwrite_output_dir: true
per_device_train_batch_size: __PER_DEVICE_TRAIN_BATCH_SIZE__
gradient_accumulation_steps: __GRADIENT_ACCUMULATION_STEPS__
learning_rate: __LEARNING_RATE__
num_train_epochs: __NUM_TRAIN_EPOCHS__
lr_scheduler_type: __LR_SCHEDULER_TYPE__
warmup_ratio: __WARMUP_RATIO__
bf16: __BF16__
save_only_model: true
eval_strategy: __EVAL_STRATEGY__
save_steps: __SAVE_STEPS__
save_total_limit: __SAVE_TOTAL_LIMIT__
report_to: __REPORT_TO__
run_name: __RUN_NAME__
